
version: '1'

services:
    app: 
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: api_vendas-app
        ports: 
            - '3333:3333'
        volumes:
            - .:/home/node/app
        depends_on:
            - db
            - redis
        
    db: 
        build: .docker/postgres
        container_name: api_vendas-db
        restart: always
        tty: true
        ports:
            - '5432:5432'
        volumes:
            - .docker/dbdata:/var/lib/postgesql/data
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=api_vendas
    
    redis:
        image: 'bitnami/redis:latest'
        container_name: api_vendas-redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    pgadmin:
        image: dpage/pgadmin4
        container_name: api_vendas-pgadmin
        tty: true
        environment: 
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '8000:80'
        depends_on:
            - db