
version: '3.8'

services:
        
    db: 
        container_name: api_vendas-db
        image: postgres
        restart: always
        tty: true
        ports:
            - 5432:5432
        volumes:
            - pgdata:/data/postgresql
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=api_vendas
    
    redis:
        image: 'bitnami/redis:latest'
        container_name: api_vendas-redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    
    app: 
        build: .
        container_name: api_vendas-app
        restart: always
        ports: 
            - 3333:3333
        volumes:
            - .:/usr/app
        links: 
            - db
            - redis
        depends_on:
            - db
            - redis

volumes:
  pgdata:
    driver: local